modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
	modId="harderores" #mandatory
	version="${version}" #mandatory
	displayName="Harder Ores" #mandatory
	authors="Draco18s" #optional
	description='''
	Basic library.
	'''
	[[dependencies.harderores]] #optional
	    modId="forge" #mandatory
	    mandatory=true #mandatory
	    versionRange="[25,)" #mandatory
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.harderores]] #optional
	    modId="hardlib" #mandatory
	    mandatory=true #mandatory
	    versionRange="[0,)" #mandatory
	    ordering="AFTER"
	    side="BOTH"
	[[dependencies.harderores]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.3]"
	    ordering="NONE"
	    side="BOTH"
[[mods]] #mandatory
	modId="hardlib" #mandatory
	version="${version}" #mandatory
	displayName="Hard Lib" #mandatory
	authors="Draco18s" #optional
	description='''
	Mining and refining ores made more consistent, interesting, and difficult. Ores will appear in structured veins, each block will be tougher to mine, and produce less resources per block.
	'''
	[[dependencies.hardlib]] #optional
	    modId="forge" #mandatory
	    mandatory=true #mandatory
	    versionRange="[25,)" #mandatory
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.hardlib]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.3]"
	    ordering="NONE"
	    side="BOTH"