modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
	modId="harderfarming" #mandatory
	version="${version}" #mandatory
	displayName="Harder Farming" #mandatory
	authors="Draco18s" #optional
	description='''
	Changes to mechanics to make farms not completely free food.
	'''
	[[dependencies.harderfarming]] #optional
	    modId="forge" #mandatory
	    mandatory=true #mandatory
	    versionRange="[25,)" #mandatory
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.harderfarming]] #optional
	    modId="hardlib" #mandatory
	    mandatory=true #mandatory
	    versionRange="[0,)" #mandatory
	    ordering="AFTER"
	    side="BOTH"
	[[dependencies.harderfarming]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4,)"
	    ordering="NONE"
	    side="BOTH"
[[mods]] #mandatory
	modId="harderores" #mandatory
	version="${version}" #mandatory
	displayName="Harder Ores" #mandatory
	authors="Draco18s" #optional
	description='''
	Mining and refining ores made more consistent, interesting, and difficult. Ores will appear in structured veins, each block will be tougher to mine, and produce less resources per block.
	'''
	[[dependencies.harderores]] #optional
	    modId="forge" #mandatory
	    mandatory=true #mandatory
	    versionRange="[25,)" #mandatory
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.harderores]] #optional
	    modId="hardlib" #mandatory
	    mandatory=true #mandatory
	    versionRange="[0,)" #mandatory
	    ordering="AFTER"
	    side="BOTH"
	[[dependencies.harderores]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4,)"
	    ordering="NONE"
	    side="BOTH"
[[mods]] #mandatory
	modId="expindustry" #mandatory
	version="${version}" #mandatory
	displayName="Exp Industry" #mandatory
	authors="Draco18s" #optional
	description='''
	Additional blocks to facilitate vanilla-style industrial operations.
	'''
	[[dependencies.expindustry]] #optional
	    modId="forge" #mandatory
	    mandatory=true #mandatory
	    versionRange="[25,)" #mandatory
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.expindustry]] #optional
	    modId="hardlib" #mandatory
	    mandatory=true #mandatory
	    versionRange="[0,)" #mandatory
	    ordering="AFTER"
	    side="BOTH"
	[[dependencies.expindustry]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4,)"
	    ordering="NONE"
	    side="BOTH"
[[mods]] #mandatory
	modId="oreflowers" #mandatory
	version="${version}" #mandatory
	displayName="Ore Flowers" #mandatory
	authors="Draco18s" #optional
	description='''
	Adds prospecting plants to the world, each indicates a specific ore found somewhere nearby.
	'''
	[[dependencies.oreflowers]] #optional
	    modId="forge" #mandatory
	    mandatory=true #mandatory
	    versionRange="[25,)" #mandatory
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.oreflowers]] #optional
	    modId="hardlib" #mandatory
	    mandatory=true #mandatory
	    versionRange="[0,)" #mandatory
	    ordering="AFTER"
	    side="BOTH"
	[[dependencies.oreflowers]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4,)"
	    ordering="NONE"
	    side="BOTH"
[[mods]] #mandatory
	modId="hardlib" #mandatory
	version="${version}" #mandatory
	displayName="Hard Lib" #mandatory
	authors="Draco18s" #optional
	description='''
	Basic library. Provides a common platform for registering blocks, items, etc. as well as integration between the various child mods and external plugins.
	'''
	[[dependencies.hardlib]] #optional
	    modId="forge" #mandatory
	    mandatory=true #mandatory
	    versionRange="[25,)" #mandatory
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.hardlib]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4,)"
	    ordering="NONE"
	    side="BOTH"